### PR TITLE
Fix for comment nuke not working in other UI languages

### PR DESCRIPTION
**Pull request by gschizas**
Unbound selector from localized value

### CODE REVIEW

**Comment by agentlame** [comment]
@Dakta can you review this and see if it's still needed after your rewrite?

**Comment by Dakta** [comment]
Heh, I made exactly this fix, totally missed this pull request: https://github.com/creesch/reddit-moderator-toolbox/commit/eb98f97c2d5f80d69421057d450d489331e83d18#diff-68fabd9e80d5e85945668d881e0ff420R54

Sorry @gschizas, didn't mean to steal your PR.

**Comment by gschizas** [comment]
No worries, just as long as it is fixed and I can return reddit to Greek UI :)

**Comment by Dakta** [comment]
If you want to do something really great, you could look for other places in the code where we have selectors and stuff that rely on the English language mode. If you can find any, open a fresh Issue for it as a general problem and we can target fixes for the next major release.

**Comment by agentlame** [comment]
Le this ^

Our internationalization is shit. Which is funny since @creesch is a Klingon.

**Comment by creesch** [comment]
True story, English content websites with an interface in my native language make me gobISuv 'e' yIwIv; bISutlh 'e' yIwIvQo'. Which goes without saying.

**Comment by dClauzel** [comment]
Bonjour !

I have the same issue with Reddit in French.

This is troublesome as this problem is not noted into the documentation.

Also, this is possibly the explanation why the removal reasons feature does not work when Reddit’s preferences are set to use the French language.

**Comment by creesch** [comment]
nah,  removal reasons work differently  so that is a different issue.

**Pull request closed without merging**
