### PR TITLE
Switch some usernotes manager stuff to .attr so it works right

### LINKED ISSUE #746: Usernote removal from the /about/usernotes page doesn't appear to work
[This line](https://github.com/creesch/reddit-moderator-toolbox/blob/master/extension/data/modules/usernotes.js#L890) (and the same deal for the remove all section) references an attribute that [doesn't exist](http://i.imgur.com/bWWifEO.png). Gonna need to add an attribute for that somewhere in that stack, probably to `.tb-un-user` so we can actually reference and use it.

### PR DESCRIPTION
**Pull request by geo1088**
This is more of a hotfix, because `.data` should be working here. But it's not, so I switched these to `.attr` instead.

Fixes #746.

### CODE REVIEW

**Comment by agentlame** [comment]
In testing did this resolve the issue?

**Comment by geo1088** [comment]
Yeah, strangely enough it did. Really weird that the `.data` wasn't setting the attribute, but that's what it was. The switch over to `.attr` has everything working perfectly now.

**Comment by agentlame** [comment]
`.data` tries to be too smart for its own good with typing.  For instance: an all numeric user name will be returned as a `Number` instead of a `String`.   It has some other oddities that I can't recall off hand.

**Comment by geo1088** [comment]
Yeah I'm googling around for causes of this, it looks like it'll try to parse everything you give it first. There's also some weird caching it does that can screw stuff up apparently... Complete guess, but I think it might have something to do with the initial `.data("user", "NONE")` on the user template. Though we're writing over that later, so I don't know...

**Comment by geo1088** [comment]
> `data` doesn't set `data-*` attributes. It manages a data cache unrelated to `data-*` attributes. It *initializes* from `data-*` attributes if there are any present, but never writes to them. To write to an attribute, use `attr`.

> --http://stackoverflow.com/a/25876307/1070107

*Ohhh.* That's probably it, then.

**Pull request merged**
