### PR TITLE
Add a content filter to the usernotes page

### PR DESCRIPTION
**Pull request by geo1088**
Requested in #726 
Adds a second live filter for the content of the usertag. Individual tags that don't match are hidden, and if a user has no matching tags, the user is hidden entirely.
CC @Pyyric

### CODE REVIEW

**Comment by agentlame** [comment]
Hrm, would it be better to have one search box that searches both fields?

**Comment by agentlame** [comment]
@creesch ^

**Comment by geo1088** [comment]
Could do that too, though I think that would probably cause some false positives if the username was the same as the tag content.

**Comment by creesch** [comment]
An argument could be made for both. But I like to separate them I think.

**Comment by agentlame** [comment]
I feel with proper labeling people will understand they are getting results for both.  It's pretty uncommon UI to have more than one search field unless they work in conjunction as parameters (ie: user comment search).  But since this is a live search, I think it should really be one box.

**Comment by creesch** [comment]
Well, that is the thing. I feel that two fields is more precise considering that it allows for specific searching. 
So even with a single field you'd still want some way to specifically search for one or the other. This is the most simple solution while others do take a bit more thought to work out.

**Comment by geo1088** [comment]
Either merging it into one box, or having 2 that work in conjunction, I'd have to rewrite a bit of the filter code so all the checks are performed at once. As it is now, only 1 of them can be used at a time - the results of the other are overwritten on keyup.

**Comment by agentlame** [comment]
Eh... I guess it's probably too much extra work for such a minor issue.  This is fine.

**Comment by geo1088** [comment]
I'll probably end up PR'ing a rewrite later, but this works for now :P

**Pull request merged**
