### PR TITLE
Remove borders from removal reasons dialog

### PR DESCRIPTION
**Pull request by geo1088**
Borders were removed from the other dialogs, this just removes the border from the RR one for consistency.

### CODE REVIEW

**Comment by creesch** [comment]
I actually did more than just that, I'll go over it in a bit.

**Comment by agentlame** [comment]
@creesch what's the word on this?

**Comment by creesch** [comment]
I'll grab this after I am done with the edge stuff.

**Comment by agentlame** [comment]
Bump

**Comment by creesch** [comment]
Fine, I'll refine it later.

**Pull request merged**
