### PR TITLE
Add "website account" feature to spam overview

### PR DESCRIPTION
**Pull request by ArrestedDevelopment**
This will add a new optional table to the spammer overview window, that'll show an overview of the website accounts (like, YouTube account, vimeo, whatever reddit has embeddable by default) a user has submitted from. Name's pretty awkward, but I wasn't sure what to call it.

This has a bunch of Promise stuff, because it was originally going to source out to embed.ly too because it's really good at getting the "author" name from various blog hosts and news sites which would be handy for spotting blogspammers, but it frustrated me with 500 errors for the past few days during testing so I gave up on that for now and gutted it. The info it gets now is simply stuff from the listing, but I might revisit this in the future 'cause this would be a handy feature imo.

If you don't want another dependency (the promise polyfill), this could be refactored to not need promises.

Seems to work fine for me in both Chrome and FF, I'm not able to test on Safari though.

### CODE REVIEW

**Comment by ArrestedDevelopment** [comment]
Looks like this sorta covers #527!

**Comment by creesch** [comment]
I'll take it for a testrun later today! Already have one question about it. 

> es6-promise.js 

Is this unmodified from the repo you got it from? This is important for firefox AMO validation.

**Comment by ArrestedDevelopment** [comment]
It is unmodified, from this archive to be precise:

https://github.com/jakearchibald/es6-promise/releases/tag/2.1.1

**Comment by creesch** [comment]
ok cool, I'll promise to also pretend to know what it does (except for *something* future ecma related).

I'll test it out once I am home, unless someone else does a yolo merge :)

**Comment by ArrestedDevelopment** [comment]
It seems to be the most highly used promise polyfills, so hopefully it won't trip up AMO validation.

Alternatively, you could choose to leave it out in the firefox version, as FF support for it seems to go pretty far back:

http://caniuse.com/#feat=promises

**Comment by agentlame** [comment]
Actually do we need it at all? It looks like all browsers support it.  Even MS Edge.

**Comment by ArrestedDevelopment** [comment]
Hmm, I'm not sure how many TB users use Chrome 31 or Safari 7, but if those browsers aren't an issue then the polyfill should be able to be axed

**Comment by creesch** [comment]
Considering that chrome is at 42 I do think we are save in that regard. Safari is a bit more tricky, but with @dakta I believe we only have a handful of safari users.

**Comment by TheEnigmaBlade** [comment]
I was helping another mod earlier with an error about Map not existing, and they were on Chrome 37 (updating to the latest version fixed their issues).

**Comment by creesch** [comment]
Well, people should be updating anyway so as long as we are aware of it I have no problem with loosing the lib.

**Comment by ArrestedDevelopment** [comment]
Axed the polyfill dependency

**Pull request merged**
